[[inputs.vsphere]]
interval = "30s"
vcenters = [ "https://indprdvc01/sdk" ]
username = "readonly@vsphere.local"
password = "P@ssw0rd@12345"
datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest" ]
insecure_skip_verify = true
cluster_metric_include = [""]
datacenter_metric_include = [""]
host_metric_exclude = [""]
vm_metric_exclude = [""]
max_query_metrics = 256
collect_concurrency = 3

[[outputs.influxdb_v2]]
urls = [ "http://influxdb:8086" ]
token = "AOLZbFm3r7UlxfXcYwcr-hMHodEWWhCYiRxGyhJ0UtlSCmW0FVgiIJ0MMR4X2IsXn3z3rX-79jP-mjIHxcXIiQ=="
organization = "mylab.local"
bucket = "VMWare"

[agent]
interval = "20s"
flush_interval = "10s"